### PR TITLE
added solutions for linked list in cpp

### PR DESCRIPTION
**Pull request by amit6663**

### CODE REVIEW

**Comment by maze-runnar** [comment]
Yes it is.

**Comment by championballer** [comment]
@amit6663 Please add the complete code files for your solutions, which includes the main function and the other libraries as well, so that these codes can function independently as well.

**Comment by amit6663** [comment]
hey guys(@maze-runnar , @championballer ) hackerrank compilor provides  rest codes.

**Comment by amit6663** [comment]
your project contains only function code why r u doing such with me only

**Comment by amit6663** [comment]
> @amit6663 Please add the complete code files for your solutions, which includes the main function and the other libraries as well, so that these codes can function independently as well.

can you provide me test cases and compilor also

**Comment by championballer** [comment]
> your project contains only function code why r u doing such illogical thing only with me.

We know that hackerrank provides rest of the codes, but this repo is meant to be a standalone code base.

Also in which codes, are only functions written? They are not consistent with the code requirements of the repository.

Also, please maintain some decorum.

**Comment by amit6663** [comment]
> > your project contains only function code why r u doing such illogical thing only with me.
> 
> We know that hackerrank provides rest of the codes, but this repo is meant to be a standalone code base.
> 
> Also in which codes, are only functions written? They are not consistent with the code requirements of the repository.
> 
> Also, please maintain some decorum.

look at your project's code

**Comment by amit6663** [comment]
> > your project contains only function code why r u doing such illogical thing only with me.
> 
> We know that hackerrank provides rest of the codes, but this repo is meant to be a standalone code base.
> 
> Also in which codes, are only functions written? They are not consistent with the code requirements of the repository.
> 
> Also, please maintain some decorum.

provide me compilor and test cases along with question remove the site links from there.

**Comment by amit6663** [comment]
yeah, Now you @championballer  can check I had added rest of codes.

**Comment by maze-runnar** [comment]
> > > your project contains only function code why r u doing such illogical thing only with me.
> > 
> > 
> > We know that hackerrank provides rest of the codes, but this repo is meant to be a standalone code base.
> > Also in which codes, are only functions written? They are not consistent with the code requirements of the repository.
> > Also, please maintain some decorum.
> 
> look at your project's code

if you got such codes mention them here , we will revert them . and also you have to follow guidelines if you want to contribute in any one's project in open source so don't get panic .

**Comment by amit6663** [comment]
> > > > your project contains only function code why r u doing such illogical thing only with me.
> > > 
> > > 
> > > We know that hackerrank provides rest of the codes, but this repo is meant to be a standalone code base.
> > > Also in which codes, are only functions written? They are not consistent with the code requirements of the repository.
> > > Also, please maintain some decorum.
> > 
> > 
> > look at your project's code
> 
> if you got such codes mention them here , we will revert them . and also you have to follow guidelines if you want to contribute in any one's project in open source so don't get panic .

hi sir @maze-runnar sorry for misbehave, i've added rest codes in files.

**Comment by maze-runnar** [comment]
@amit6663 you read me link is showing 404 , please correct them . And other links in linked list section

**Comment by maze-runnar** [comment]
> @amit6663 your readme link is showing 404 , please correct them . And other links in linked list section

i have corrected the link , for the next time check the link properly :)

**Pull request merged**
