### PR TITLE
Added Array Manipulation Solution

### PR DESCRIPTION
**Pull request by championballer**
The question can be referred to here. https://www.hackerrank.com/challenges/crush/problem?h_l=interview&playlist_slugs%5B%5D=interview-preparation-kit&playlist_slugs%5B%5D=arrays

### CODE REVIEW

**Comment by maze-runnar** [comment]
Rename the file to Array_manipulation.cpp

**Comment by maze-runnar** [comment]
Good work.!!

**Comment by maze-runnar** [comment]
If you can update read me then please update it and make it better and open a seperate pr for that.

**Comment by championballer** [comment]
Sure, will look into it. @maze-runnar

**Pull request merged**
