### PR TITLE
 Birthday Cake Candle.cpp

### PR DESCRIPTION
**Pull request by gaursakshi**

### CODE REVIEW

**Comment by gaursakshi** [comment]
I tried to update the readme can you please help in this please

**Comment by championballer** [comment]
What problem are you facing?

**Comment by gaursakshi** [comment]
I updated the readme.md  but  was unable to make the word done as hyperlink  in c++ column

**Comment by championballer** [comment]
Okay so, as you must already might have noticed, the bars act as column separators. To mark the question as completed you need to go into that column, write [Done](link of the code). Makes sense?

**Comment by gaursakshi** [comment]
hey i am very sorry  to bother you but i am unable to do this and if my code is not merged how i can give my link for my corresponding program in  read me.Please help me

**Comment by championballer** [comment]
@gaursakshi Please have a look once. You were not linking the file right. Otherwise everything was good.

**Comment by gaursakshi** [comment]
thank you i got it and thanks for the help.Hope you will merge the pr

**Pull request merged**
