### PR TITLE
Added codes for Trees, Stack and Queues. Corrected Link for Linked List.

### PR DESCRIPTION
**Pull request by amit6663**

### CODE REVIEW

**Comment by amit6663** [comment]
sir @maze-runnar I've successfully added all codes of Trees, if did something wrong let me know, otherwise merge it, thank you

**Comment by maze-runnar** [comment]
@amit6663  add main function in ` Trees/IsBinarySearchTree.cpp`
Every thing else is fine .

**Comment by championballer** [comment]
@maze-runnar Will review this once @amit6663 makes the changes you asked for.

**Comment by amit6663** [comment]
> @amit6663 add main function in ` Trees/IsBinarySearchTree.cpp`
> Every thing else is fine .

sir I could not able to add rest code becoz compilor gives error even after spending more time. But sir u can see Trees/isThisABST.py file it has also contain only the function code.
Sir, if u r agree pls merge otherwise tell me to delete that specific file,

**Comment by amit6663** [comment]
> LGTM.

sir @championballer what is LGTM?

**Comment by championballer** [comment]
Looks good to me.

**Comment by maze-runnar** [comment]
@amit resolve conflicts , so that i can merge

**Comment by amit6663** [comment]
> @amit6663 resolve conflicts , so that i can merge

sir @maze-runnar i resolved it

**Pull request merged**
