### PR TITLE
Java solutions for warm-up challenges

### PR DESCRIPTION
**Pull request by AatmikJain**

### CODE REVIEW

**Comment by maze-runnar** [comment]
> Hey @AatmikJain, do you think it would be possible for you to update the README as well, and mark the java codes as completed. That would help other contributors willing to contribute to this project know the questions already solved. @maze-runnar what do you think?
It's reasonable.  @AatmikJain  make suere to update read me .

**Comment by maze-runnar** [comment]
yeah that's cool !

**Comment by maze-runnar** [comment]
@AatmikJain  update the read me .

**Comment by AatmikJain** [comment]
Oh yeah! I'll surely do that right now

**Comment by AatmikJain** [comment]
Done

**Pull request merged**
