### PR TITLE
added all codes for warm up challenges, dictionaries and hashmaps, sorting, string manipulation and greedy algorithms

### PR DESCRIPTION
**Pull request by amit6663**

### CODE REVIEW

**Comment by maze-runnar** [comment]
@championballer  it's ok for the time , may be solve such complexity issues later .

**Comment by maze-runnar** [comment]
please check if every thing else is working .

**Comment by amit6663** [comment]
> @amit6663 The readme contains the warm up questions twice in your PR. Please correct that. All else looks good to me. Really great job.

sir @championballer i didn't find, look good to me README file

**Comment by championballer** [comment]
Screenshot 2020-01-05 at 12 03 03 AM
Screenshot 2020-01-05 at 12 03 15 AM

Have a look once? @amit6663

**Comment by amit6663** [comment]
> Screenshot 2020-01-05 at 12 03 03 AM
> Screenshot 2020-01-05 at 12 03 15 AM
> 
> Have a look once? @amit6663

sir @championballer issue had solved.

**Pull request merged**
