### PR TITLE
added code for Balanced Forest and solved issue #63

### PR DESCRIPTION
**Pull request by amit6663**

### CODE REVIEW

**Comment by amit6663** [comment]
I think I created complicated pull request again, is it right?. sir @championballer , @maze-runnar

**Comment by RashakDude** [comment]
@amit6663 You need to add some more fields for the Javascript column :)

**Comment by championballer** [comment]
@amit6663 No your local repo is not rebased hence this shows so many commits. Please rebase to your own cloned repo. Close this and open a new PR.

**Comment by amit6663** [comment]
> @amit6663 No your local repo is not rebased hence this shows so many commits. Please rebase to your own cloned repo. Close this and open a new PR.

okay sir i try

**Pull request closed without merging**
